name: Create Pull Request on Tag from Feature Branches

on: workflow_dispatch
#   push:
#     tags:
#       - "v*"
#     branches:
#       - feature/*

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main # Il branch di destinazione della pull request (ad esempio 'main')
          commit-message: "Automatic PR: Merge tag ${GITHUB_REF#refs/tags/} from feature branch"
          title: "Pull Request: Merge feature branch into main"
          body: |
            This pull request was created automatically after pushing a tag to a feature branch.

            **Tag:** ${GITHUB_REF#refs/tags/}
