name: Check Modified Files on Push

on:
  push:
    branches:
      - main # Puoi specificare i branch su cui vuoi attivare il controllo

jobs:
  check_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Recupera tutta la cronologia git

      - name: List modified files
        run: |
          echo "Modified files:"
          git diff HEAD^ HEAD
