name: Pull Request Workflow
on:
  pull_request:
    types: [closed] # Il workflow viene attivato quando viene aperta una pull request o quando viene aggiornata una pull request esistente.

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: first-step
        run: echo "Hello Pull Request"
  second-job:
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - name: first-step
        run: echo "Hello Pull Request 2"
